### ISSUE TITLE
R doesn't list all system requirements in DESCRIPTION's SystemRequirements.

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/r-system-requirements#70]
This suggestion has been moved from https://github.com/r-lib/remotes/issues/558.  This submission repeats most of the first submission there, with a few changes based on the discussion which followed.

The `RcppArmadillo` package currently requires C++11.  This should be available by default in R 4+, but in earlier R versions it needs to be requested.  Rather than using `SystemRequirements` in `DESCRIPTION` to do it, `RcppArmadillo` puts `CXX_STD = CXX11` in `src/Makevars.in`, which is the recommended way according to Writing R Extensions, section  1.2.4.

However, `remotes::system_requirements()` misses the requirement, so (as discussed in this thread:  https://stat.ethz.ch/pipermail/r-package-devel/2020q4/006327.html) Github Action builds of packages using `RcppArmadillo` in earlier versions of R fail.  `remotes::system_requirements()` queries the `r-system-requirements` database, so I've moved the suggestion here.

Suggestion:  make the database entries look at `Makevars.*` as well as `DESCRIPTION`, or maybe just apply a special-case rule to `RcppArmadillo` (though there are about 500 other CRAN packages with  `CXX_STD = CXX11` in `Makevars.*` and no `SystemRequirements` entry).

**Comment by glin** [comment]
Hi, this is an interesting issue, thanks for reporting it. From reading through the linked threads, I think the best way to solve this is for the rstpm2 package to add `CXX_STD = CXX11` to their `Makevars.*` file, or `SystemRequirements: C++11` to their `DESCRIPTION` file. Then, the GitHub Actions builds should just work.

The system requirements DB *could* look for C++11 in the `Makevars`/`DESCRIPTION` files of a package's `LinkingTo` dependencies perhaps, and recommend adding `CXX_STD = CXX11` to a user-level `Makevars` or similar. However, this isn't something that users typically do (or should have to do) when installing packages, so I think it's better for packages to follow R's recommended way of enabling C++11 support in R <= 3.6.

**Comment by dmurdoch** [comment]
The problem is that the C++11 dependency isn't due to anything under the control of the `rstpm2` package author, it's purely in the `RcppArmadillo` package that it depends on.  As he said, 
```
Moreover, as a principle, should a package need to change the Makevars
and DESCRIPTION files to suit the most recent updates of their
dependencies? 
```
There are also those other ~500 packages doing the same thing as `RcppArmadillo`, and your advice would apply to their reverse dependencies too.

I think the best solution here would be for R Core to make the specification of dependencies more consistent (and I've suggested this on Bugzilla), or to provide a function to list the dependencies, found everywhere they might be given.  However, R moves slowly, so it would probably be faster for someone in this project to put in a workaround.

**Comment by glin** [comment]
It does seem like a lot of packages fail to compile because of this. Just looking at `RcppArmadillo`'s reverse LinkingTo dependencies, our build logs for R 3.5 on Ubuntu 16 show that 266/789 reverse dependencies failed to build due to `C++11 compiler required`. Full list for reference at https://gist.github.com/glin/9770dfce2c33937b0d374fb512a918de - it includes some widely used packages like `forecast`.

I agree there's enough impact to justify a workaround, but I'm not sure how. Adding `CXX_STD = CXX11` to `~/.R/Makevars` or `R_HOME/etc/Makevars.site` as I suggested earlier doesn't actually work, at least for `rstpm2`. The only good way I could find to enable C++11 support was to set the `R_PKG_CXX_STD` environment variable to `CXX11`, but that's not a publicly documented method. Do you know if there's a better way to set `CXX_STD = CXX11` without modifying the package's `Makevars` file?

As an alternative, we could also build binary packages for Ubuntu 16 with something like `CXX='$(CXX11) $(CXX11STD)'` in `etc/Makeconf`. Anyone using RStudio Package Manager as the CRAN mirror would then get working binaries, including GitHub Actions users. However, that wouldn't help if the package has to be installed from source, like in the case of building `rstpm2` on GitHub Actions, or if not using RSPM binaries.

So I still think package authors should add `SystemRequirements: C++11` to their package if they can. It's a small effort for a huge user experience improvement, and much easier than trying to work around the issue in external tools.

> I think the best solution here would be for R Core to make the specification of dependencies more consistent (and I've suggested this on Bugzilla)

100% yes!! And thanks for suggesting it there.

**Comment by dmurdoch** [comment]
I don't know much about automatic builds of packages.  I had been hoping that all that was needed was for "C++11" (or some similar string) to show up in the database entry for `RcppArmadillo` so that `remotes::system_requirements()` would find it, and the Github Actions build would include a compatible compiler.

**Comment by glin** [comment]
Oh, to clear up any possible confusion: in the GitHub Actions builds for Ubuntu 16, a C++11 compatible compiler is already installed. The problem is that the gcc version there isn't new enough to have C++11 enabled by default, so you need to explicitly enable it with a `-std=c++11` flag. However, that flag is typically added by package authors via declaring `SystemRequirements: C++11` in the DESCRIPTION file.

For example, building rstpm2 on Ubuntu 16 / R 3.5 with gcc installed fails by default:
```sh
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ Rscript -e 'install.packages("rstpm2", repos = "https://cloud.r-project.org")'
trying URL 'https://cloud.r-project.org/src/contrib/rstpm2_1.5.1.tar.gz'
Content type 'application/x-gzip' length 2042667 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

* installing *source* package ‘rstpm2’ ...
** package ‘rstpm2’ successfully unpacked and MD5 sums checked
** libs
gcc -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2  -c RuniqueCombs.c -o RuniqueCombs.o
g++  -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2  -c aft.cpp -o aft.o
In file included from /opt/R/3.5.3/lib/R/library/RcppArmadillo/include/armadillo:21:0,
                 from /opt/R/3.5.3/lib/R/library/RcppArmadillo/include/RcppArmadilloForward.h:49,
                 from /opt/R/3.5.3/lib/R/library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from aft.cpp:1:
/opt/R/3.5.3/lib/R/library/RcppArmadillo/include/armadillo_bits/compiler_check.hpp:50:4: error: #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
   #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
    ^
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /opt/R/3.5.3/lib/R/library/RcppArmadillo/include/armadillo:28,
                 from /opt/R/3.5.3/lib/R/library/RcppArmadillo/include/RcppArmadilloForward.h:49,
                 from /opt/R/3.5.3/lib/R/library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from aft.cpp:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
```

Setting `CXX_STD = CXX11` in R makes it work:
```sh
$ R_PKG_CXX_STD=CXX11 Rscript -e 'install.packages("rstpm2", repos = "https://cloud.r-project.org")'
trying URL 'https://cloud.r-project.org/src/contrib/rstpm2_1.5.1.tar.gz'
Content type 'application/x-gzip' length 2042667 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

* installing *source* package ‘rstpm2’ ...
** package ‘rstpm2’ successfully unpacked and MD5 sums checked
** libs
gcc -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2  -c RuniqueCombs.c -o RuniqueCombs.o
g++ -std=gnu++11 -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2 -c aft.cpp -o aft.o
gcc -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2  -c bspline.c -o bspline.o
g++ -std=gnu++11 -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2 -c c_optim.cpp -o c_optim.o
...
```

The challenge is that the system requirement is already installed, but just not enabled, and I haven't seen a good way to enable it from the user's perspective. Setting the `R_PKG_CXX_STD=CXX11` environment variable or modifying your `etc/Makeconf` file feels like a hack.

At least this doesn't seem to be a problem on Ubuntu 18 or 20 though, where gcc is new enough to not require the `-std=c++11` flag:
```sh
# Ubuntu 18, R 3.5.3: rstpm2 installs from source successfully by default
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ Rscript -e 'install.packages("rstpm2", repos = "https://cloud.r-project.org")'
trying URL 'https://cloud.r-project.org/src/contrib/rstpm2_1.5.1.tar.gz'
Content type 'application/x-gzip' length 2042667 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

* installing *source* package ‘rstpm2’ ...
** package ‘rstpm2’ successfully unpacked and MD5 sums checked
** libs
gcc -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2  -c RuniqueCombs.c -o RuniqueCombs.o
g++  -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2  -c aft.cpp -o aft.o
gcc -I"/opt/R/3.5.3/lib/R/include" -DNDEBUG  -I"/opt/R/3.5.3/lib/R/library/Rcpp/include" -I"/opt/R/3.5.3/lib/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -g -O2  -c bspline.c -o bspline.o
...
```

So if this problem is too hard to solve, users could switch to a newer Linux distro in their GitHub Actions builds, like [Ubuntu 20](https://github.com/r-lib/actions/blob/438639f2dbe3231530d3d41978035ac4ff38785f/examples/check-standard.yaml#L27-L28), and avoid this issue completely.

**Comment by kevinushey** [comment]
Ubuntu 16 will also be reaching EOL soon (April 30th, 2021), so expending a large amount of effort to support it might not be worth it.

**Comment by glin** [comment]
@kevinushey Good point, so I think we'll just not worry about this for now. As a stopgap, RStudio Package Manager is now building R <= 3.5 binary packages with C++11 enabled by default on Ubuntu 16, so at least users of RSPM or https://packagemanager.rstudio.com won't be hitting this issue. About 1/3 of RcppArmadillo's reverse dependencies were built from this change, including the forecast and rstpm2 packages.
